name: library_success
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.2
  font_awesome_flutter: ^10.1.0
  provider: ^6.0.3
  cloud_firestore: ^3.1.17
  http: ^0.13.4
  fluttertoast: ^8.0.9
  animated_background: ^2.0.0
  shimmer: ^2.0.0
  html: ^0.15.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  sqflite: ^2.0.2+1
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.6.1
  path: ^1.8.1
  connectivity_plus: ^2.3.5
  internet_connection_checker: ^0.0.1+4


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/fonts/Roboto-Light.ttf


  uses-material-design: true

